/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.7/userguide/multi_project_builds.html
 */

rootProject.name = "kuberig-crd-dsl"

pluginManagement {
    val kuberigDslVersion : String by settings

    plugins {
        id("io.kuberig.dsl.generator") version(kuberigDslVersion)
    }

    repositories {
        mavenLocal()
        jcenter()
        maven("https://dl.bintray.com/teyckmans/rigeldev-oss-maven")
        gradlePluginPortal()
    }
}


include("tektoncd-pipeline")
include("cloudstate")
include("cert-manager")
include("knative-serving")
include("knative-eventing")